### ISSUE TITLE
mapreduce result wont change 

### ISSUE THREAD

**Issue by at15** [at15/forum-search#12]
when I put new data and run map reduce, the generated the result is still the same. and in rm manager, I saw 120 map but only 1 reduce.

btw: now datanode won't start ...

**Comment by at15** [comment]
aaaaa ! after changed to non-yarn mode , got the log

```
15/11/17 21:14:19 WARN tokenizer.DiscuzThreadTokenizer: wrong json format for thread 
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "valid" (class cn.edu.sjtu.at15.forum.crawler.processor.discuz.DiscuzThread), not marked as ignorable (6 known properties: "replyCount", "title", "viewCount", "author", "url", "authorPost"])
 at [Source: {"url":"http://www.1point3acres.com/bbs/thread-147141-1-1.html","title":"lettcode刷一遍要多少天？","viewCount":622,"replyCount":11,"author":"Struggling","authorPost":"注册一亩三分地论坛，查看更多干货！ 您需要 登录 才可以下载或查看，没有帐号？获取更多干货，注册来地里当农民！ x 请问下，大家刷leetcode大概多少天刷一遍？参考参考","valid":true}; line: 1, column: 260] (through reference chain: cn.edu.sjtu.at15.forum.crawler.processor.discuz.DiscuzThread["valid"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:836)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1330)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:262)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2714)
        at cn.edu.sjtu.at15.forum.tokenizer.DiscuzThreadTokenizer.tokenizeThread(DiscuzThreadTokenizer.java:68)
        at cn.edu.sjtu.at15.forum.indexer.ThreadTokenizeMapper.map(ThreadTokenizeMapper.java:23)
        at cn.edu.sjtu.at15.forum.indexer.ThreadTokenizeMapper.map(ThreadTokenizeMapper.java:14)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```

all the other thread got the `valid` attr, which should be ignored ...
